source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'rails-i18n'
gem 'simple_form'
gem 'show_for'
